---
- name: validate states on EOS devices
  hosts: DC1
  connection: httpapi
  gather_facts: false
  collections:
    - arista.avd

  tasks:
    - name: validate states on EOS devices
      import_role:
        name: arista.avd.eos_validate_state
      vars:
        fabric_name: "FABRIC"
        root_dir: 'FABRIC-Information'
        structured_dir: 'intended/structured_configs' 

#    - name: Upload verification reports to github
#      uses: actions/upload-artifact@master
#      with:
#        name: ValidationReport
#        path: FABRIC-information/reports/