name: 'Dev Runner'

on:
  push:
#    branches-ignore:
#      - main

# on:
#   push:

jobs:
  avd-dev-deployment:
    runs-on: [self-hosted, dev]
    # test2
    # hellp
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master

      # - name: Build Configurations
      #   run: ansible-playbook -i inventory.yml build.yml

      - name: Deploy Configuration to CVP
        run: ansible-playbook -i inventory.yml deploy-cvp.yml

      - run: sleep 10

      - name: Validate connectivity
        run: ansible-playbook -i inventory.yml fabric-validation.yml

      - name: Upload verification reports to github
        uses: actions/upload-artifact@master
        with:
          name: ValidationReport
          # path: FABRIC-information/reports/
          path: reports/

