name: 'Prod Runner'

on:
  pull_request:
    types:
      - closed

jobs:
  merged:
    if: github.event.pull_request.merged == true
    runs-on: [self-hosted, prod]
    steps:
      - run: echo The PR was merged

      - name: Checkout Repository
        uses: actions/checkout@master

      - name: Deploy Configurations to ACT
        run: ansible-playbook -i inventory/inventory.yml playbooks/prod-fabric-deploy.yml
